import { Tour } from '@/types/tour';

export const tours: Tour[] = [
  {
    id: '1',
    slug: 'hot-air-balloon-ride',
    category: 'balloon',
    difficulty: 'easy',
    price: 180,
    originalPrice: 220,
    duration: '3 hours',
    groupSize: { min: 2, max: 20 },
    ageRestriction: { min: 6 },
    rating: 4.9,
    reviewCount: 342,
    featured: true,
    active: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1591825944920-9a51ce5e0f07?w=1200&h=800&fit=crop',
        alt: 'Hot air balloons over Cappadocia',
        width: 1200,
        height: 800,
      },
      {
        url: 'https://images.unsplash.com/photo-1608211805656-f46ee1a39729?w=1200&h=800&fit=crop',
        alt: 'Balloon ride sunrise view',
        width: 1200,
        height: 800,
      },
      {
        url: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&h=800&fit=crop',
        alt: 'Multiple balloons in the sky',
        width: 1200,
        height: 800,
      },
    ],
    translations: {
      tr: {
        title: 'Kapadokya Sıcak Hava Balonu Turu',
        shortDescription: 'Gün doğumunda Kapadokya\'nın büyüleyici manzarasını kuşbakışı izleyin',
        description: 'Kapadokya\'nın eşsiz peri bacalarını ve vadilerini sıcak hava balonuyla keşfedin. Gün doğumunda başlayan bu unutulmaz deneyim, size Kapadokya\'nın tüm güzelliğini kuşbakışı sunacak. Profesyonel pilotlarımız eşliğinde güvenli ve konforlu bir yolculuk yapacaksınız.',
        highlights: [
          'Gün doğumunda muhteşem manzara',
          'Profesyonel ve deneyimli pilotlar',
          'Şampanya ikramı ve uçuş sertifikası',
          'Otel transfer hizmeti dahil',
          'Küçük grup garantisi (Max 20 kişi)',
        ],
        itinerary: [
          {
            title: 'Otel Alımı',
            description: 'Sabah 04:30-05:00 arası otelinizdeki alım',
            time: '04:30 - 05:00',
          },
          {
            title: 'Balon Sahası',
            description: 'Hafif kahvaltı ve balon hazırlığının izlenmesi',
            time: '05:30',
          },
          {
            title: 'Uçuş',
            description: '45-60 dakikalık muhteşem balon turu',
            time: '06:00 - 07:00',
          },
          {
            title: 'Kutlama',
            description: 'İniş sonrası şampanya ikramı ve sertifika töreni',
            time: '07:15',
          },
          {
            title: 'Otel Dönüşü',
            description: 'Kahvaltınız için vaktinde otelinize dönüş',
            time: '08:00',
          },
        ],
        included: [
          'Otel transfer hizmeti (Göreme, Uçhisar, Avanos bölgesi)',
          '45-60 dakika balon uçuşu',
          'Uçuş öncesi hafif kahvaltı',
          'Uçuş sonrası şampanya ikramı',
          'Uçuş sertifikası',
          'Tam sigorta',
        ],
        notIncluded: [
          'Kişisel harcamalar',
          'Göreme merkezi dışı oteller için ekstra transfer ücreti',
          'Fotoğraf ve video çekimi (opsiyonel)',
        ],
        importantInfo: [
          'Hava koşullarına bağlı olarak tur iptal edilebilir',
          'Hamile bayanlara tavsiye edilmez',
          '6 yaş altı çocuklar kabul edilmemektedir',
          'Rahat kıyafetler ve spor ayakkabılar giyiniz',
          'Sabah erken saatlerde hava serin olabilir, yanınıza bir ceket alınız',
        ],
        metaTitle: 'Kapadokya Sıcak Hava Balonu Turu | %20 İndirim',
        metaDescription: 'Kapadokya\'da unutulmaz bir balon turu deneyimi. Gün doğumunda peri bacalarını keşfedin. Profesyonel pilotlar, tam sigorta, şampanya ikramı dahil.',
        metaKeywords: ['kapadokya balon turu', 'sıcak hava balonu', 'kapadokya gezilecek yerler'],
      },
      en: {
        title: 'Cappadocia Hot Air Balloon Ride',
        shortDescription: 'Experience the magical landscape of Cappadocia from above at sunrise',
        description: 'Discover the unique fairy chimneys and valleys of Cappadocia by hot air balloon. This unforgettable experience starting at sunrise will offer you a bird\'s eye view of all the beauty of Cappadocia. You will have a safe and comfortable journey with our professional pilots.',
        highlights: [
          'Breathtaking sunrise views',
          'Professional and experienced pilots',
          'Champagne toast and flight certificate',
          'Hotel transfer included',
          'Small group guarantee (Max 20 people)',
        ],
        itinerary: [
          {
            title: 'Hotel Pick-up',
            description: 'Morning pick-up from your hotel between 04:30-05:00',
            time: '04:30 - 05:00',
          },
          {
            title: 'Balloon Site',
            description: 'Light breakfast and watching balloon preparation',
            time: '05:30',
          },
          {
            title: 'Flight',
            description: '45-60 minutes magnificent balloon tour',
            time: '06:00 - 07:00',
          },
          {
            title: 'Celebration',
            description: 'Champagne toast and certificate ceremony after landing',
            time: '07:15',
          },
          {
            title: 'Hotel Return',
            description: 'Return to your hotel in time for breakfast',
            time: '08:00',
          },
        ],
        included: [
          'Hotel transfer service (Göreme, Uçhisar, Avanos area)',
          '45-60 minute balloon flight',
          'Light breakfast before flight',
          'Champagne toast after flight',
          'Flight certificate',
          'Full insurance',
        ],
        notIncluded: [
          'Personal expenses',
          'Extra transfer fee for hotels outside Göreme center',
          'Photo and video shooting (optional)',
        ],
        importantInfo: [
          'Tour may be cancelled due to weather conditions',
          'Not recommended for pregnant women',
          'Children under 6 years old are not accepted',
          'Wear comfortable clothes and sports shoes',
          'It can be cool in early morning hours, bring a jacket',
        ],
        metaTitle: 'Cappadocia Hot Air Balloon Ride | 20% Discount',
        metaDescription: 'An unforgettable balloon tour experience in Cappadocia. Discover fairy chimneys at sunrise. Professional pilots, full insurance, champagne toast included.',
        metaKeywords: ['cappadocia balloon tour', 'hot air balloon', 'things to do in cappadocia'],
      },
    },
  },
  {
    id: '2',
    slug: 'red-green-valley-tour',
    category: 'cultural',
    difficulty: 'easy',
    price: 45,
    duration: 'Full day',
    groupSize: { min: 4, max: 14 },
    rating: 4.8,
    reviewCount: 189,
    featured: true,
    active: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1541480601022-2308c0f02487?w=1200&h=800&fit=crop',
        alt: 'Red Valley Cappadocia',
        width: 1200,
        height: 800,
      },
      {
        url: 'https://images.unsplash.com/photo-1570939274717-7eda259b50ed?w=1200&h=800&fit=crop',
        alt: 'Underground city',
        width: 1200,
        height: 800,
      },
    ],
    translations: {
      tr: {
        title: 'Kızıl ve Yeşil Vadi Turu',
        shortDescription: 'Kapadokya\'nın en güzel vadilerini ve yeraltı şehirlerini keşfedin',
        description: 'Kapadokya\'nın tarih kokan vadilerinde unutulmaz bir gün geçirin. Derinkuyu Yeraltı Şehri, Ihlara Vadisi ve Selime Katedrali gibi muhteşem yerleri ziyaret edin.',
        highlights: [
          'Derinkuyu Yeraltı Şehri gezisi',
          'Ihlara Vadisi yürüyüşü (4 km)',
          'Selime Manastırı ziyareti',
          'Yerel restoranda öğle yemeği',
          'Küçük grup turu',
        ],
        itinerary: [
          {
            title: 'Otel Alımı',
            description: 'Sabah 09:30 otel alımı',
            time: '09:30',
          },
          {
            title: 'Derinkuyu Yeraltı Şehri',
            description: '8 katlı yeraltı şehrini keşfedin',
            time: '10:30 - 11:30',
          },
          {
            title: 'Ihlara Vadisi',
            description: 'Nehir kenarında yürüyüş ve doğa',
            time: '12:00 - 14:00',
          },
          {
            title: 'Öğle Yemeği',
            description: 'Vadi kenarında yerel lezzetler',
            time: '14:00 - 15:00',
          },
          {
            title: 'Selime Manastırı',
            description: 'Kaya oyma manastır kompleksi',
            time: '15:30 - 16:30',
          },
          {
            title: 'Otel Dönüşü',
            description: 'Göreme\'ye dönüş',
            time: '18:00',
          },
        ],
        included: [
          'Profesyonel rehber',
          'Klimalı araç transferi',
          'Öğle yemeği',
          'Müze giriş ücretleri',
        ],
        notIncluded: [
          'İçecekler',
          'Kişisel harcamalar',
        ],
        importantInfo: [
          'Rahat yürüyüş ayakkabıları giyin',
          'Su ve şapka yanınıza alın',
          'Orta seviye fitness gerektirir',
        ],
        metaTitle: 'Kızıl ve Yeşil Vadi Turu | Kapadokya',
        metaDescription: 'Kapadokya\'nın en güzel vadilerini keşfedin. Yeraltı şehri, Ihlara Vadisi ve daha fazlası.',
      },
      en: {
        title: 'Red and Green Valley Tour',
        shortDescription: 'Explore the most beautiful valleys and underground cities of Cappadocia',
        description: 'Spend an unforgettable day in the historical valleys of Cappadocia. Visit magnificent places like Derinkuyu Underground City, Ihlara Valley and Selime Cathedral.',
        highlights: [
          'Derinkuyu Underground City tour',
          'Ihlara Valley hiking (4 km)',
          'Selime Monastery visit',
          'Lunch at local restaurant',
          'Small group tour',
        ],
        itinerary: [
          {
            title: 'Hotel Pick-up',
            description: 'Morning pick-up at 09:30',
            time: '09:30',
          },
          {
            title: 'Derinkuyu Underground City',
            description: 'Explore the 8-level underground city',
            time: '10:30 - 11:30',
          },
          {
            title: 'Ihlara Valley',
            description: 'Riverside walk and nature',
            time: '12:00 - 14:00',
          },
          {
            title: 'Lunch',
            description: 'Local cuisine by the valley',
            time: '14:00 - 15:00',
          },
          {
            title: 'Selime Monastery',
            description: 'Rock-carved monastery complex',
            time: '15:30 - 16:30',
          },
          {
            title: 'Hotel Return',
            description: 'Return to Göreme',
            time: '18:00',
          },
        ],
        included: [
          'Professional guide',
          'Air-conditioned vehicle transfer',
          'Lunch',
          'Museum entrance fees',
        ],
        notIncluded: [
          'Drinks',
          'Personal expenses',
        ],
        importantInfo: [
          'Wear comfortable walking shoes',
          'Bring water and hat',
          'Requires moderate fitness level',
        ],
        metaTitle: 'Red and Green Valley Tour | Cappadocia',
        metaDescription: 'Discover the most beautiful valleys of Cappadocia. Underground city, Ihlara Valley and more.',
      },
    },
  },
  {
    id: '3',
    slug: 'atv-sunset-tour',
    category: 'adventure',
    difficulty: 'moderate',
    price: 65,
    duration: '2 hours',
    groupSize: { min: 2, max: 10 },
    ageRestriction: { min: 16 },
    rating: 4.7,
    reviewCount: 156,
    featured: true,
    active: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop',
        alt: 'ATV tour in Cappadocia',
        width: 1200,
        height: 800,
      },
    ],
    translations: {
      tr: {
        title: 'ATV ile Gün Batımı Turu',
        shortDescription: 'Gün batımında ATV ile vadilerde heyecan dolu bir macera',
        description: 'ATV ile Kapadokya\'nın çarpıcı manzaralarını keşfedin. Gün batımı sırasında kızıl kayalıklar arasında unutulmaz bir deneyim yaşayın.',
        highlights: [
          'Profesyonel ATV eğitimi',
          'Güvenlik ekipmanları dahil',
          'Gün batımı manzarası',
          'Fotoğraf molaları',
        ],
        itinerary: [
          {
            title: 'Buluşma ve Eğitim',
            description: 'ATV kullanım eğitimi',
            time: '16:30',
          },
          {
            title: 'Vadi Turu',
            description: 'Kızılçukur ve Güvercinlik vadileri',
            time: '17:00 - 18:30',
          },
          {
            title: 'Gün Batımı',
            description: 'Panoramik gün batımı noktası',
            time: '18:30 - 19:00',
          },
        ],
        included: [
          'ATV kirası',
          'Kask ve gözlük',
          'Profesyonel rehber',
          'Sigorta',
        ],
        notIncluded: [
          'Otel transferi',
          'Kişisel harcamalar',
        ],
        importantInfo: [
          'Sürücü belgesi gereklidir',
          '16 yaş altı kabul edilmez',
          'Tozlu ortam olduğu için uygun kıyafet giyin',
        ],
        metaTitle: 'ATV Gün Batımı Turu | Kapadokya',
        metaDescription: 'ATV ile Kapadokya vadilerinde gün batımı macerası. Profesyonel eğitim ve ekipman dahil.',
      },
      en: {
        title: 'ATV Sunset Tour',
        shortDescription: 'An exciting adventure through valleys on ATV at sunset',
        description: 'Discover the striking landscapes of Cappadocia on ATV. Experience an unforgettable adventure among red rocks during sunset.',
        highlights: [
          'Professional ATV training',
          'Safety equipment included',
          'Sunset view',
          'Photo stops',
        ],
        itinerary: [
          {
            title: 'Meeting and Training',
            description: 'ATV usage training',
            time: '16:30',
          },
          {
            title: 'Valley Tour',
            description: 'Red and Rose valleys',
            time: '17:00 - 18:30',
          },
          {
            title: 'Sunset',
            description: 'Panoramic sunset point',
            time: '18:30 - 19:00',
          },
        ],
        included: [
          'ATV rental',
          'Helmet and goggles',
          'Professional guide',
          'Insurance',
        ],
        notIncluded: [
          'Hotel transfer',
          'Personal expenses',
        ],
        importantInfo: [
          'Driver\'s license required',
          'Under 16 not accepted',
          'Wear appropriate clothes for dusty environment',
        ],
        metaTitle: 'ATV Sunset Tour | Cappadocia',
        metaDescription: 'Sunset adventure in Cappadocia valleys on ATV. Professional training and equipment included.',
      },
    },
  },
];
